version: "3.8"
services:
  app:
    build:
      context: . # Use the current directory (BACKEND) as the build context
      dockerfile: Dockerfile
    container_name: crm-be-uapa
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    env_file:
      - .env.dev # Load environment variables from .env.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ~/.aws:/root/.aws:ro
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
